DenverCoder1/custom-icon-badges

- README.md
> Simplified Heroku steps

- .gitignore
- server/controllers/controller.ts
- server/services/logoColor.ts
> Added logoColor support for SVGs

- .github/workflows/release.yml
- .github/workflows/stale.yml
release.yml - automated releases
stale.yml - mark and close inactive issues
> Add stale and release workflows

- server/services/logoColor.ts
> Add color aliases from shields.io

- client/src/FileUpload.tsx
- client/src/UploadForm.tsx
- server/controllers/controller.ts
Before:
After:
----
Before:
After:
----
Before:
After:
> More detailed form responses

- README.md
Added all octicons link and added phone icon to readme
Updated example of how to use
> docs: added more icons

- .gitignore
- server/controllers/controller.ts
- server/routes/routes.ts
- server/services/iconDatabase.ts
Added JSON endpoint to display all icons in the database
https://custom-icon-badges.herokuapp.com/list.json
> feat: Added JSON endpoint for complete icon list

- README.md
> docs: Make links to stargazers, issues, license

- client/package.json
- package.json
- server/controllers/controller.ts
> Removed missing logo error and fixed status codes

- server/services/badgeUrl.ts
> Re-encode request params to allow symbols such as hash

- README.md
[![streak][1]][1]
[![total][2]][2]
[1]: https://custom-icon-badges.herokuapp.com/badge/dynamic/json?logo=fire&logoColor=fff&color=orange&label=github%20streak&query=%24.currentStreak.length&suffix=%20days&url=https%3A%2F%2Fgithub-readme-streak-stats.herokuapp.com%2F%3Fuser%3DDenverCoder1%26type%3Djson 
[2]: https://custom-icon-badges.herokuapp.com/badge/dynamic/json?logo=graph&logoColor=fff&color=blue&label=total%20contributions&query=%24.totalContributions&url=https%3A%2F%2Fgithub-readme-streak-stats.herokuapp.com%2F%3Fuser%3DDenverCoder1%26type%3Djson
> Added streak stats badge examples

- server/controllers/controller.ts
- server/services/fetchBadges.ts
> Disallow overwriting simpleicon slugs

- server/controllers/controller.ts
- server/services/fetchBadges.ts
- server/services/iconDatabase.ts
> Return too big error if shields.io can't load the icon

- client/src/FileUpload.tsx
- client/src/UploadForm.tsx
- server/controllers/controller.ts
Removed client-side file size verification - The 8kb limit was arbitrary and it can only really be verified by checking the response code of the request
API trigger error message if shields.io url for the badge returns any 400+ error code.
> Improved shields api error detection

- client/src/UploadForm.scss
- client/src/UploadForm.tsx
- add loading animation 
Fixes #99
Test on Local at http://localhost:5000/
> feat: implement loading when submitting the form

- README.md
Adds info about using simple icons on badges
> docs: Add simple icons to readme

- README.md
> docs(readme): Add pygame to miscellaneous logos

- client/src/UploadForm.tsx
Update the UploadForm operation to use async/await syntax entirely. Right now it uses a mix of `await` and `then` chaining which is inconsistent.
Checklist:
> refactor: Update UploadForm to entirely use async/await syntax

- package.json
- yarn.lock
Reverts DenverCoder1/custom-icon-badges#651
> Revert "chore(deps): bump axios from 1.1.3 to 1.2.0"

- README.md
> docs(readme) Added Made with TypeScript badge

- README.md
> docs(readme): Make upload icon link to demo site

- client/src/FileUpload.tsx
- client/src/TextBox.tsx
Fixed the muted text so it appears on a dark background
> fix: change color of input box labels

- client/src/index.tsx
> refactor: Replace ReactDOM.render with createRoot

- .github/dependabot.yml
> ci: Group dependency updates

- client/package.json
- client/yarn.lock
- package.json
- yarn.lock
> chore(deps): Update eslint dependencies

- README.md
> docs(readme): change star badge color to black
